### PR TITLE
Custom options

### PR DESCRIPTION
**Pull request by devkpv**
Function getOpts() was have bug with accept custom options. Small fix.

### CODE REVIEW

**Comment by devkpv** [comment]
@kartik-v pls review PR

**Comment by devkpv** [comment]
@kartik-v are you a live?

**Comment by kartik-v** [comment]
Give me some time to review and will update

**Comment by devkpv** [comment]
Yes, of course. No problem!

**Comment by devkpv** [comment]
@kartik-v Can you adding tag 1.0.3?

**Pull request merged**
